from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(564, 446)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.countryInputLabel = QtWidgets.QLabel(Form)
        self.countryInputLabel.setObjectName("countryInputLabel")
        self.verticalLayout_2.addWidget(self.countryInputLabel)
        self.jsonTextBox = QtWidgets.QLineEdit(Form)
        self.jsonTextBox.setObjectName("jsonTextBox")
        self.verticalLayout_2.addWidget(self.jsonTextBox)
        self.jsonTB = QtWidgets.QToolButton(Form)
        self.jsonTB.setObjectName("jsonTB")
        self.verticalLayout_2.addWidget(self.jsonTB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.pointsInputLabel = QtWidgets.QLabel(Form)
        self.pointsInputLabel.setObjectName("pointsInputLabel")
        self.verticalLayout_2.addWidget(self.pointsInputLabel)
        self.linearOutputTextbox = QtWidgets.QLineEdit(Form)
        self.linearOutputTextbox.setObjectName("linearOutputTextbox")
        self.verticalLayout_2.addWidget(self.linearOutputTextbox)
        self.linearOutputTB = QtWidgets.QToolButton(Form)
        self.linearOutputTB.setObjectName("linearOutputTB")
        self.verticalLayout_2.addWidget(self.linearOutputTB)
        self.outputLocationLabel = QtWidgets.QLabel(Form)
        self.outputLocationLabel.setObjectName("outputLocationLabel")
        self.verticalLayout_2.addWidget(self.outputLocationLabel)
        self.arealFeatureTextbox = QtWidgets.QLineEdit(Form)
        self.arealFeatureTextbox.setObjectName("arealFeatureTextbox")
        self.verticalLayout_2.addWidget(self.arealFeatureTextbox)
        self.arealOutputTB = QtWidgets.QToolButton(Form)
        self.arealOutputTB.setObjectName("arealOutputTB")
        self.verticalLayout_2.addWidget(self.arealOutputTB)
        self.submitPushButton = QtWidgets.QPushButton(Form)
        self.submitPushButton.setObjectName("submitPushButton")
        self.verticalLayout_2.addWidget(self.submitPushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Features Extract Tool"))
        self.countryInputLabel.setText(_translate("Form", "Input Open Street Maps JSON File:"))
        self.jsonTextBox.setToolTip(_translate("Form", "Accepts a shapefile with a field of \'NAME\'"))
        self.jsonTB.setToolTip(_translate("Form", ".shp File Browser"))
        self.jsonTB.setText(_translate("Form", "..."))
        self.pointsInputLabel.setText(_translate("Form", "Output Location for Linear Features: "))
        self.linearOutputTextbox.setToolTip(_translate("Form", "Accepts a shapefile with a field of \'shop\'"))
        self.linearOutputTB.setToolTip(_translate("Form", ".shp File Browser"))
        self.linearOutputTB.setText(_translate("Form", "..."))
        self.outputLocationLabel.setText(_translate("Form", "Output Location for Areal Features:"))
        self.arealFeatureTextbox.setToolTip(_translate("Form", "Output location displayed as full filepath"))
        self.arealOutputTB.setToolTip(_translate("Form", "\'Save As\' File Browser"))
        self.arealOutputTB.setText(_translate("Form", "..."))
        self.submitPushButton.setToolTip(_translate("Form", "Click this only after completing all other fields"))
        self.submitPushButton.setText(_translate("Form", "Submit"))

